### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#11]
## Acceptance Criteria

- [ ] A user can sign in using existing credentials
- [ ] A user can sign in using 3rd party SSO
- [ ] The system can associate and identify a user after a login flow, store their auth identity (ie..token) and use that identity to authenticate requests to different APIs
- [ ] A user is requested to login before completing a desired action
