### ISSUE TITLE
Migration of existing NewSpring Apollos UI components

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#12]
## Acceptance criteria

- [x] Determine strategy for migrating components over (do we try to move all at once? as needed, etc)
- [x] Tests and stories
- [x] What refactoring do we want to do? Recompose vs recompact, etc
