### ISSUE TITLE
A user can create an account from within the app

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#135]
## TODO

- [ ] Generate design asset to reflect UI

Rough mockup:

![image](https://user-images.githubusercontent.com/103927/42836608-1eedb64e-89c1-11e8-85dd-408bde4b658c.png)

spacing / padding probably isn't right...this is rough. But I think this could be nice.

-----

## User Story

A user wants to easily sign up for a new account from within the app.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] A user can create an account from within the app
* [ ] Turn the login screen to a two-tab view (similar to NS/Apollos) with Login on one tag, Signup on the other

**Comment by conrad-vanl** [comment]
@IsaacHardy I plan to start building out the UI on this today, hoping I can get to it :-D

My current plan, let me know thoughts:

1. The [auth/index](https://github.com/ApollosProject/apollos-prototype/blob/master/mobile/src/auth/index.js) component will render a tab view with the Sign up and Login forms
1. I'll add an `auth/signup` form similar to [`auth/login`](https://github.com/ApollosProject/apollos-prototype/tree/master/mobile/src/auth/login)
1. [This bit](https://github.com/ApollosProject/apollos-prototype/blob/master/mobile/src/auth/login/index.js#L15-L19) should be taken out of the login form and moved into a client-side graphql mutation in our client-side graphql [resolver](https://github.com/ApollosProject/apollos-prototype/blob/master/mobile/src/store/index.js), so that it can be easily called from both the login and signup components

**Comment by IsaacHardy** [comment]
I think that plan sounds pretty great!
