### ISSUE TITLE
A user can watch a static live stream in app

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#43]
## TODO:

- [ ] Capture a live now mockup from newspring to use as example

--------

## User Story

A user can watch a static ("fake") live stream in the app

#### Problem Details _(Optional)_

* @conrad-vanl created a Church Online Platform account for Apollos. He can give you credentials
* We may not be able to show a real church online platform live stream???                       

#### Acceptance Criteria _(Optional)_

* [ ] The app will be live all the time (for now) in the app
* [ ] The app will feature a "Live Now" banner just like NewSpring
* [ ] Tapping on the "Live Now" banner will open a modal webview with the ChOP player
* [ ] This issue is only for the UI side - essentially displaying a ChOP player in the app with static/hard-coded endpoints
* [ ] MVP is to use a webview like NewSpring

**Comment by cdanwards** [comment]
@conrad-vanl Do you have the credentials for the Church Online Platform account?

**Comment by cdanwards** [comment]
@conrad-vanl I've got a live now button up and working, and also have the modal through React Navigation working. Need to clean up styling and put the button on all the different tabs. Wanted to get some feedback and make sure this was what you had in mind. I've upload on branch 43-live-video.

**Comment by conrad-vanl** [comment]
@cdanwards I'll start looking at it. Go ahead and open a PR for it too to make ti easier to  get 👀 on it :) (and I can make comments on line numbers if needed).

I would open the PR, but then you wouldn't get credit once it's merged ;-)
