### ISSUE TITLE
Build static UI for next steps menu

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#45]
## TODO

- [x] flush out designs in next steps menu
- [x] flush out issue criteria

------

## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by conrad-vanl** [comment]
Closing and replacing with #65
