### ISSUE TITLE
Schema Design: Content

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#6]
## TODO

- [ ] This issue needs to have acceptance criteria flushed out

## Acceptance Criteria

- [ ] Can query for a single content item
- [ ] Can query for a list of content items by content channel
- [ ] Designed spec for initial content data points (such as title, content, etc)
