### ISSUE TITLE
[EPIC] Create and hookup Auth route

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#77]
Create an auth route that we can use to point the user to login/sign up. For now, lets focus on just login and hook up a login view to the `authenticate` mutation created in #42

Lets focus on functionality for now and we can handle aesthetics in a second pass.

#### Acceptance Criteria

* [ ] Add a link to the connect screen that opens an auth modal
* [ ] When signed in this link becomes a sign-out link (we'll make this better in the future)
* [ ] A user can login in the auth modal
* [ ] Logging into the auth modal takes you back to wherever you were before
* [ ] Authentication state is persisted across app reloads

#### Potentially helpful things

There's a handful of tutorials around the interwebs on react-navigation authentication. Most of them are about handling an app that forces you to login, so not entirely helpful.  We can start small and focus primarily on hooking up the login view, and build from there in future issues. This might be most helpful: https://medium.com/the-react-native-log/building-an-authentication-flow-with-react-navigation-fb5de2203b5c

It might make sense to use apollo-link-state https://www.apollographql.com/docs/link/links/state.html to handle certain client-side state here...like whether or not a user is logged in and to get the current auth token. I think the plan is to continue integrating with apollo-link-state as our direct replacement for how most apps utilize Redux. Utilizing apollo-link-state is not required for this task though, I don't believe, but can be considered if we run into questions with how to store user state with the token and such.

Login form: we used `formik` in newspring/apollos and created all of our forms in separate components. This kind of got unwieldy and hard to maintain. I think we can contain forms inside of our screens, or atleast close by (ex: `auth/LoginForm` and `auth/LoginScreen`)

The other long-term requirements of authentication that might be important to consider from a design implementation frame-set, but are not apart of this issue:

- Routes that require authentication. Need a way to link to a route, but upon navigating to that route, the user is forced to login. If they cancel login, they go back
- Functions that require authentication. Like tapping on a heart icon.
