### ISSUE TITLE
A user can watch the live-stream in app (frontend only)

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#8]
## TODO

- [ ] This is a 32 point issue. Needs to be broken up into sub-issues

## Acceptance Criteria

- [ ] Determine potential live stream integration points (what does their API look like, what will we need to do to integrate with them).
- [ ] Build static UI into demo app
