### ISSUE TITLE
Show user profile on connect screen

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#88]
## TODO

- [ ] Needs new/updated design mockup

-----

## User Story

As a user I want to know the app knows who I am, and begin to associate space within the app as "my own".

#### Problem Details _(Optional)_

![image.png](https://images.zenhubusercontent.com/55bcf69f4f7a08fbb7f4086a/92362459-a5c4-4398-905b-0ac81ce0a845)

#### Acceptance Criteria _(Optional)_

* [ ] It should show the user's profile photo
* [ ] It should show the user's name
* [ ] Create issues for adding the ability to edit your profile and change your profile photo

**Comment by conrad-vanl** [comment]
@IsaacHardy I think as a first pass at this, I think you could just plainly render out the user's avatar, name, and hometown above the connect menu:

![image](https://user-images.githubusercontent.com/103927/42946100-b5971332-8b2f-11e8-97f3-234bd2fb690d.png)

Long term - I'd like to figure out how we should be constructing/laying out this screen. I'm working on figuring that out (from a design perspective)...if you or anyone else would like to help/contribute to that  - please let me know 😀

**Comment by IsaacHardy** [comment]
@conrad-vanl Thanks for the details. I don't mind discussing and researching the connect screen design with you.

**Comment by IsaacHardy** [comment]
@conrad-vanl Do you know the color or the background in the image above? Is it a part of our theme?

**Comment by conrad-vanl** [comment]
Yeah, but don't worry about including it. It can be white too or whatever it is currently. That background color wasn't purposefully set

**Comment by IsaacHardy** [comment]
@conrad-vanl It doesn't seem that a location exists on the Rock's Person object. In Heighliner, we used a method that searched a groups location that a person was connected to. 

``` js
async getHomesFromId(id, { cache } = { cache: true }) {
    return await this.cache.get(
      `${id}:PersonHomes`,
      () =>
        GroupLocation.find({
          where: { GroupLocationTypeValueId: 19 }, // Home
          attributes: [],
          include: [
            { model: Location.model },
            {
              model: Group.model,
              attributes: [],
              where: { GroupTypeId: 10 }, // Family
              include: [
                {
                  model: GroupMember.model,
                  where: { PersonId: `${id}` },
                  attributes: [],
                },
              ],
            },
          ],
        }).then(x => x.map(y => y.Location)),
      { cache },
    );
  }
```

This means we will have to find an alternative way to find a user's location which I think might be out of scope of this story.

**Comment by conrad-vanl** [comment]
Yup! In that case, `location` is totally out of scope for this story :)
