### ISSUE TITLE
A user can watch the live-stream in app

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-prototype#9]
## Acceptance Criteria

- [ ] Determine live stream integration point - Church Online Platform - (what does their API look like, what will we need to do to integrate with them).
- [ ] Build static UI into demo app: persistent "Apollos Church is live" banner that upon tapping, opens a live stream view
- [ ] Build data connectors and schema for Church Online Platform
- [ ] Connect static UI to data backend
